<?php
# CHECKS TO SEE IF THERE ARE ADMINS SHOWING AS LOGGED INTO CHAT TOOL - BUT WHO HAVEN'T HAD  ALIVE UPDATE IN TIMEFRAME
# MEANING THAT THEY HAVE CLOSED A BROWSER WINDOW WITHOUT LOGGING OUT
# THIS CRON RUNS EVERY 5 MINUTES

$OBJ = new Chat_Chat();
$OBJ->ClearAbandonedAdmin();
?>